# Generated by Django 2.2.1 on 2019-05-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190520_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Utilizatori'},
        ),
    ]
